### ISSUE TITLE
AWS GovCloud Regions 

### ISSUE THREAD

**Issue by BClev** [rkoval/alfred-aws-console-services-workflow#43]
This workflow works great for standard AWS regions, but AWS GovCloud (us-gov-east-1 and us-gov-west-1) has a slightly different base URL than the standard regions:
`https://{region}.console.amazonaws-us-gov.com/`

Would it be possible for there to be either a changeable config or check that if the region has us-gov*, the workflow sends you to the correct GovCloud base URL instead of `{region}.console.aws.amazon.com` please?

**Comment by BClev** [comment]
Shame on me for missing the README piece that helps with this (the env var). It does work when you use the ALRED_AWS_CONSOLE_SERVICES_WORKFLOW_AWS_CONSOLE_DOMAIN env var. Only caveat is the var has misspelling (ALRED instead of ALFRED like the others) which made it not work because, once again on me, I changed it to ALFRED instead of just leaving as-is from the README. Hope this issue helps others out there.

**Comment by rkoval** [comment]
ahhh blast! sorry that tripped you up, but thanks for calling it out. i'm drafting up a release with some breaking changes sometime this week, so i can probably fix this as part of that since it's technically a breaking change.

additionally, this new release will contain logic that will use the us-gov domain when the workflow detects a `us-gov-*` region is in use (like if this is set in your aws config file). i don't think you should need the env var override with this functionality; however, i don't have access to `us-gov-*` regions, so i can't fully test it. regardless, i'll let you know when this is released.

**Comment by rkoval** [comment]
hokay, both of these are out with [v5.0.0](https://github.com/rkoval/alfred-aws-console-services-workflow/releases/tag/v5.0.0). i'm going to close this issue out in the meantime, but let me know if you're still having issues with it.
